# Arquivo de configuração de automação do Codemagic
workflows:
  web-and-android-build:
    name: Compilação Web e Android Jogo Inclusivo
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Buscar dependências do projeto
        script: |
          flutter pub get
      - name: Compilar versão Web do Jogo
        script: |
          flutter build web --release
      - name: Compilar arquivo de instalação do Android (APK)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/web/**
